# Generated by Django 5.2.10 on 2026-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blotter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blottercase",
            name="dismissal_reason",
            field=models.TextField(blank=True, help_text="Reason for dismissal"),
        ),
        migrations.AddField(
            model_name="blottercase",
            name="settlement_details",
            field=models.TextField(
                blank=True, help_text="Terms of agreement if settled"
            ),
        ),
        migrations.AddField(
            model_name="historicalblottercase",
            name="dismissal_reason",
            field=models.TextField(blank=True, help_text="Reason for dismissal"),
        ),
        migrations.AddField(
            model_name="historicalblottercase",
            name="settlement_details",
            field=models.TextField(
                blank=True, help_text="Terms of agreement if settled"
            ),
        ),
    ]
