services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - bims_data:/app/data
    env_file:
      - .env
      - BIMS_PROFILE=production
      - PROD_DEBUG=False
    restart: always

volumes:
  bims_data:
