import os
import subprocess
import sys
import shutil

# BIMS2 Hardened Packaging Tool
# This script uses PyArmor for obfuscation and Nuitka for compilation.
# Requirements: pip install pyarmor nuitka

def run_command(command, description):
    print(f"\n>>> {description}...")
    try:
        subprocess.check_call(command, shell=True)
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Command failed: {e}")
        return False
    return True

def package_hardened():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    dist_dir = os.path.join(base_dir, "dist_hardened")
    
    if os.path.exists(dist_dir):
        shutil.rmtree(dist_dir)
    os.makedirs(dist_dir)

    print("--- Starting Hardened Build Pipeline ---")

    # 0. Generate Embedded Secrets for Production
    print("\n>>> Generating Embedded Secrets...")
    secure_env_content = f"""# Generated by package_hardened.py - DO NOT EDIT
DEBUG = False
SECRET_KEY = 'django-insecure-{os.urandom(32).hex()}'
ALLOWED_HOSTS = '*'
SECURE_SSL_REDIRECT = False
LICENSE_DEBUG_BYPASS = False
BIMS_PORTABLE_MODE = False
BIMS_DATA_ROOT = 'C:/BIMS_Data'
"""
    secure_env_path = os.path.join(base_dir, "config", "env_secure.py")
    with open(secure_env_path, 'w') as f:
        f.write(secure_env_content)

    # Set environment variable for Nuitka/Django context
    os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings.prod'

    # 1. Compile Main Application with Nuitka (C++)
    # This compiles EVERYTHING (runner + apps + config) into machine code.
    nuitka_cmd = (
        "python -m nuitka "
        "--standalone "
        "--assume-yes-for-downloads "
        "--zig "
        "--include-package=apps "
        "--include-package=config "
        "--include-package=django "
        "--include-package=whitenoise "
        "--module-parameter=django-settings-module=config.settings.prod "
        "--output-dir=dist_hardened/build "
        "--output-filename=waitress_server "
        "waitress_server.py"
    )
    
    if not run_command(nuitka_cmd, "Compiling Standalone C++ Binary with Nuitka"):
        print("[ERROR] Nuitka compilation failed.")
        return

    # 2. Compile Update Engine with Nuitka (C++)
    update_cmd = (
        "python -m nuitka "
        "--standalone "
        "--assume-yes-for-downloads "
        "--zig "
        "--output-dir=dist_hardened/build "
        "--output-filename=BIMS_Update "
        "update_engine.py"
    )
    run_command(update_cmd, "Compiling Update Engine with Nuitka")

    # 3. Finalize Distribution Folder
    print("\n>>> Finalizing distribution...")
    
    # Run collectstatic for production-grade static serving
    print("\n>>> Generating production static assets...")
    run_command("python manage.py collectstatic --noinput --clear", "Running collectstatic")
    
    # Nuitka puts the result in dist_hardened/build/waitress_server.dist/
    # We want the CONTENTS of that folder in dist_hardened/ directly
    server_dist = os.path.join(dist_dir, "build", "waitress_server.dist")
    if os.path.exists(server_dist):
        for item in os.listdir(server_dist):
            s = os.path.join(server_dist, item)
            d = os.path.join(dist_dir, item)
            if os.path.isdir(s):
                if os.path.exists(d): shutil.rmtree(d)
                shutil.copytree(s, d)
            else:
                if not os.path.exists(d): # Don't overwrite if already copied
                    shutil.copy2(s, d)

    # Do the same for BIMS_Update (it will share DLLs usually, but we copy the bin)
    update_dist = os.path.join(dist_dir, "build", "update_engine.dist")
    if os.path.exists(update_dist):
        shutil.copy2(os.path.join(update_dist, "BIMS_Update.exe"), os.path.join(dist_dir, "BIMS_Update.exe"))

    # Copy Static, Templates, and newly generated staticfiles
    shutil.copytree("static", os.path.join(dist_dir, "static"), dirs_exist_ok=True)
    shutil.copytree("templates", os.path.join(dist_dir, "templates"), dirs_exist_ok=True)
    if os.path.exists("staticfiles"):
        shutil.copytree("staticfiles", os.path.join(dist_dir, "staticfiles"), dirs_exist_ok=True)
    
    # Copy essential files
    shutil.copy2("manage.py", dist_dir)
    shutil.copy2("VERSION", dist_dir)

    # Final Cleanup: Remove the massive build folder to keep the installer lean
    print("\n>>> Cleaning up build artifacts...")
    if os.path.exists(os.path.join(dist_dir, "build")):
        shutil.rmtree(os.path.join(dist_dir, "build"))

    print("\n========================================")
    print("   System Build Ready for Installer!")
    print(f"   Location: {dist_dir}")
    print("========================================")

if __name__ == "__main__":
    package_hardened()
