# Generated by Django 5.2.10 on 2026-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='tier',
            field=models.CharField(choices=[('community', 'Community (Free/Basic)'), ('pro', 'Pro (Advanced)'), ('ultra', 'Ultra (Premium/GIS)')], default='community', max_length=20),
        ),
    ]
