# Generated by Django 5.2.10 on 2026-02-25 06:24

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/external-certs/', location='C:\\Users\\komradkat\\Documents\\Repos\\bims2\\media\\certificates\\issued'), upload_to='%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
