# Generated by Django 5.2.10 on 2026-02-25 12:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0006_alter_certificate_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/external-certs/", location="C:\\BIMS_Data\\certificates"
                ),
                upload_to="%Y/%m/",
            ),
        ),
    ]
