# Generated by Django 5.2.10 on 2026-01-29 08:25

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text="e.g. Jr., Sr., III", max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("citizenship", models.CharField(default="Filipino", max_length=50)),
                ("place_of_birth", models.CharField(blank=True, max_length=200)),
                ("religion", models.CharField(blank=True, max_length=100)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "educational_attainment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elementary_level", "Elementary Level"),
                            ("elementary_graduate", "Elementary Graduate"),
                            ("high_school_level", "High School Level"),
                            ("high_school_graduate", "High School Graduate"),
                            ("college_level", "College Level"),
                            ("college_graduate", "College Graduate"),
                            ("vocational", "Vocational"),
                            ("post_graduate", "Post-Graduate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("self_employed", "Self-Employed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200)),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "philhealth_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="PhilHealth Number"
                    ),
                ),
                (
                    "sss_gsis_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SSS/GSIS Number"
                    ),
                ),
                (
                    "tin_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="TIN Number"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                ("purok", models.CharField(help_text="Purok/Sitio", max_length=100)),
                (
                    "address",
                    models.CharField(help_text="House Number/Street", max_length=500),
                ),
                (
                    "years_of_residency",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("is_household_head", models.BooleanField(default=True)),
                (
                    "relationship_to_head",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to household head (if not head)",
                        max_length=50,
                    ),
                ),
                ("is_senior_citizen", models.BooleanField(default=False)),
                ("is_pwd", models.BooleanField(default=False, verbose_name="Is PWD")),
                ("disability_type", models.CharField(blank=True, max_length=200)),
                ("is_solo_parent", models.BooleanField(default=False)),
                (
                    "is_4ps",
                    models.BooleanField(default=False, verbose_name="Is 4Ps Member"),
                ),
                ("is_indigent", models.BooleanField(default=False)),
                ("is_voter", models.BooleanField(default=False)),
                ("precinct_number", models.CharField(blank=True, max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="residents/photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set to False for deceased or moved out"
                    ),
                ),
                (
                    "household_head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if this person is the household head",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="household_members",
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident",
                "verbose_name_plural": "Residents",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("head", "Household Head"),
                            ("spouse", "Spouse"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("in_law", "In-Law"),
                            ("grandchild", "Grandchild"),
                            ("grandparent", "Grandparent"),
                            ("other_relative", "Other Relative"),
                            ("boarder", "Boarder/Helper"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_membership_as_head",
                        to="residents.resident",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_membership_as_member",
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household Member",
                "verbose_name_plural": "Household Members",
            },
        ),
        migrations.CreateModel(
            name="HistoricalResident",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text="e.g. Jr., Sr., III", max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("citizenship", models.CharField(default="Filipino", max_length=50)),
                ("place_of_birth", models.CharField(blank=True, max_length=200)),
                ("religion", models.CharField(blank=True, max_length=100)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "educational_attainment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elementary_level", "Elementary Level"),
                            ("elementary_graduate", "Elementary Graduate"),
                            ("high_school_level", "High School Level"),
                            ("high_school_graduate", "High School Graduate"),
                            ("college_level", "College Level"),
                            ("college_graduate", "College Graduate"),
                            ("vocational", "Vocational"),
                            ("post_graduate", "Post-Graduate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("self_employed", "Self-Employed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200)),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "philhealth_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="PhilHealth Number"
                    ),
                ),
                (
                    "sss_gsis_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SSS/GSIS Number"
                    ),
                ),
                (
                    "tin_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="TIN Number"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                ("purok", models.CharField(help_text="Purok/Sitio", max_length=100)),
                (
                    "address",
                    models.CharField(help_text="House Number/Street", max_length=500),
                ),
                (
                    "years_of_residency",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("is_household_head", models.BooleanField(default=True)),
                (
                    "relationship_to_head",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to household head (if not head)",
                        max_length=50,
                    ),
                ),
                ("is_senior_citizen", models.BooleanField(default=False)),
                ("is_pwd", models.BooleanField(default=False, verbose_name="Is PWD")),
                ("disability_type", models.CharField(blank=True, max_length=200)),
                ("is_solo_parent", models.BooleanField(default=False)),
                (
                    "is_4ps",
                    models.BooleanField(default=False, verbose_name="Is 4Ps Member"),
                ),
                ("is_indigent", models.BooleanField(default=False)),
                ("is_voter", models.BooleanField(default=False)),
                ("precinct_number", models.CharField(blank=True, max_length=20)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set to False for deceased or moved out"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household_head",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Leave blank if this person is the household head",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Resident",
                "verbose_name_plural": "historical Residents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHouseholdMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("head", "Household Head"),
                            ("spouse", "Spouse"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("in_law", "In-Law"),
                            ("grandchild", "Grandchild"),
                            ("grandparent", "Grandparent"),
                            ("other_relative", "Other Relative"),
                            ("boarder", "Boarder/Helper"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household_head",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="residents.resident",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Household Member",
                "verbose_name_plural": "historical Household Members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="resident",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="residents_r_last_na_09bdf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resident",
            index=models.Index(fields=["purok"], name="residents_r_purok_f727b4_idx"),
        ),
        migrations.AddIndex(
            model_name="resident",
            index=models.Index(
                fields=["is_active"], name="residents_r_is_acti_2375eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="householdmember",
            unique_together={("household_head", "member")},
        ),
    ]
