# Generated by Django 5.2.10 on 2026-02-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresident",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalresident",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate", null=True
            ),
        ),
    ]
