# Generated by Django 5.2.10 on 2026-01-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="License key string", max_length=255, unique=True
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("community", "Community"),
                            ("pro", "Pro"),
                            ("ultra", "Ultra"),
                        ],
                        help_text="License tier level",
                        max_length=20,
                    ),
                ),
                (
                    "hardware_id",
                    models.CharField(
                        blank=True,
                        help_text="Hardware ID this license is bound to",
                        max_length=255,
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date license was issued"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="License expiration date (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether license is active"
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5, help_text="Maximum number of users allowed"
                    ),
                ),
            ],
            options={
                "verbose_name": "License Key",
                "verbose_name_plural": "License Keys",
                "ordering": ["-issued_date"],
            },
        ),
    ]
