# Generated by Django 5.2.10 on 2026-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_licensekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the Barangay', max_length=200)),
                ('address', models.TextField(help_text='Complete address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barangay/logo/')),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('captain_name', models.CharField(max_length=200, verbose_name='Barangay Captain')),
                ('secretary_name', models.CharField(blank=True, max_length=200, verbose_name='Barangay Secretary')),
                ('treasurer_name', models.CharField(blank=True, max_length=200, verbose_name='Barangay Treasurer')),
                ('is_setup_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Barangay Information',
                'verbose_name_plural': 'Barangay Information',
            },
        ),
    ]
