# Generated by Django 5.2.10 on 2026-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barangayinfo_structured_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayinfo',
            name='captain_name',
            field=models.CharField(blank=True, help_text='Full name of the Punong Barangay (used on printed certificates)', max_length=200),
        ),
    ]
