# Generated by Django 5.2.10 on 2026-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_captain_name_to_barangayinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('punong_barangay', 'Punong Barangay'), ('kagawad', 'Barangay Kagawad'), ('sk_chairman', 'SK Chairman'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('lupong_tagapamayapa', 'Lupong Tagapamayapa'), ('other', 'Other')], max_length=30)),
                ('committee', models.CharField(blank=True, choices=[('', '— None —'), ('peace_order', 'Peace & Order'), ('health', 'Health & Sanitation'), ('education', 'Education & Culture'), ('infrastructure', 'Infrastructure'), ('livelihood', 'Livelihood & Entrepreneurship'), ('environment', 'Environment & Natural Resources'), ('finance', 'Finance & Appropriation'), ('women', 'Women & Family'), ('youth', 'Youth & Sports'), ('senior', 'Senior Citizen Affairs')], max_length=50)),
                ('honorific', models.CharField(blank=True, help_text='e.g. Hon., Dr.', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='e.g. Jr., Sr.', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/photos/')),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barangay Official',
                'verbose_name_plural': 'Barangay Officials',
                'ordering': ['order', 'position', 'last_name'],
            },
        ),
    ]
