# Generated by Django 5.2.10 on 2026-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_barangayinfo_captain_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangayinfo",
            name="logo_base64",
            field=models.TextField(
                blank=True,
                help_text="Base64 encoded logo for standalone persistence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="barangayinfo",
            name="logo_mimetype",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
