# Generated by Django 5.2.10 on 2026-02-13 20:58

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("owner_address", models.TextField(blank=True)),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Business Address"),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "permit_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "dti_sec_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="DTI/SEC Registration Number",
                    ),
                ),
                (
                    "tin",
                    models.CharField(blank=True, max_length=50, verbose_name="TIN"),
                ),
                ("nature_of_business", models.CharField(blank=True, max_length=100)),
                ("cedula_number", models.CharField(blank=True, max_length=50)),
                ("cedula_date", models.DateField(blank=True, null=True)),
                (
                    "gross_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "clearance_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("or_number", models.CharField(blank=True, max_length=50)),
                ("issued_date", models.DateField(default=django.utils.timezone.now)),
                ("expiration_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Permit",
                "verbose_name_plural": "Business Permits",
                "ordering": ["-expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="BusinessClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("or_number", models.CharField(max_length=50)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearances",
                        to="business.businesspermit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBusinessClearance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("or_number", models.CharField(max_length=50)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("issued_date", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="business.businesspermit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical business clearance",
                "verbose_name_plural": "historical business clearances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBusinessPermit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("owner_address", models.TextField(blank=True)),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Business Address"),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "permit_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "dti_sec_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="DTI/SEC Registration Number",
                    ),
                ),
                (
                    "tin",
                    models.CharField(blank=True, max_length=50, verbose_name="TIN"),
                ),
                ("nature_of_business", models.CharField(blank=True, max_length=100)),
                ("cedula_number", models.CharField(blank=True, max_length=50)),
                ("cedula_date", models.DateField(blank=True, null=True)),
                (
                    "gross_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "clearance_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("or_number", models.CharField(blank=True, max_length=50)),
                ("issued_date", models.DateField(default=django.utils.timezone.now)),
                ("expiration_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Business Permit",
                "verbose_name_plural": "historical Business Permits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
