# Generated by Django 5.2.10 on 2026-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('police', 'Police Station'), ('fire', 'Fire Station'), ('hospital', 'Hospital / Clinic')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Service',
                'verbose_name_plural': 'Emergency Services',
                'ordering': ['service_type', 'name'],
            },
        ),
    ]
