# Generated by Django 5.2.10 on 2026-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyservice",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
